// Code generated by mockery v2.32.4. DO NOT EDIT.

package ports

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// KeyGenService is an autogenerated mock type for the KeyGenService type
type KeyGenService struct {
	mock.Mock
}

type KeyGenService_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyGenService) EXPECT() *KeyGenService_Expecter {
	return &KeyGenService_Expecter{mock: &_m.Mock}
}

// GenerateKey provides a mock function with given fields: ctx
func (_m *KeyGenService) GenerateKey(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyGenService_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type KeyGenService_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KeyGenService_Expecter) GenerateKey(ctx interface{}) *KeyGenService_GenerateKey_Call {
	return &KeyGenService_GenerateKey_Call{Call: _e.mock.On("GenerateKey", ctx)}
}

func (_c *KeyGenService_GenerateKey_Call) Run(run func(ctx context.Context)) *KeyGenService_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *KeyGenService_GenerateKey_Call) Return(_a0 string, _a1 error) *KeyGenService_GenerateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeyGenService_GenerateKey_Call) RunAndReturn(run func(context.Context) (string, error)) *KeyGenService_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeyGenService creates a new instance of KeyGenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyGenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyGenService {
	mock := &KeyGenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
