// Code generated by mockery v2.32.4. DO NOT EDIT.

package ports

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenerService is an autogenerated mock type for the ShortenerService type
type ShortenerService struct {
	mock.Mock
}

type ShortenerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortenerService) EXPECT() *ShortenerService_Expecter {
	return &ShortenerService_Expecter{mock: &_m.Mock}
}

// GetLongURL provides a mock function with given fields: ctx, key
func (_m *ShortenerService) GetLongURL(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_GetLongURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLongURL'
type ShortenerService_GetLongURL_Call struct {
	*mock.Call
}

// GetLongURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *ShortenerService_Expecter) GetLongURL(ctx interface{}, key interface{}) *ShortenerService_GetLongURL_Call {
	return &ShortenerService_GetLongURL_Call{Call: _e.mock.On("GetLongURL", ctx, key)}
}

func (_c *ShortenerService_GetLongURL_Call) Run(run func(ctx context.Context, key string)) *ShortenerService_GetLongURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerService_GetLongURL_Call) Return(_a0 string, _a1 error) *ShortenerService_GetLongURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_GetLongURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ShortenerService_GetLongURL_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function with given fields: ctx, url
func (_m *ShortenerService) Shorten(ctx context.Context, url string) (string, error) {
	ret := _m.Called(ctx, url)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenerService_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type ShortenerService_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *ShortenerService_Expecter) Shorten(ctx interface{}, url interface{}) *ShortenerService_Shorten_Call {
	return &ShortenerService_Shorten_Call{Call: _e.mock.On("Shorten", ctx, url)}
}

func (_c *ShortenerService_Shorten_Call) Run(run func(ctx context.Context, url string)) *ShortenerService_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShortenerService_Shorten_Call) Return(_a0 string, _a1 error) *ShortenerService_Shorten_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShortenerService_Shorten_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ShortenerService_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortenerService creates a new instance of ShortenerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenerService {
	mock := &ShortenerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
